Buttons:
  confirm:                                              [1079,857,11,9]
  rebet:                                                [953,856,10,9]
  cancel:                                               [822,852,11,12]

Lobby:
  center:                                               [955,474,10,11]

InGame:
  balance:                                              [265,162,259,43]
  chatbox:                                              [1420,910,269,92]
  chat-input:                                           [1450,1009,200,20]
  digitalmsg:                                           [790,371,359,65]

  emoji icon:                                           [1411,1007,28,21]
  emojis:
    - [1054,895,35,25]
    - [1151,897,23,22]
    - [1250,897,34,29]
    - [1363,901,35,19]
    - [1126,952,51,23]
    - [1257,953,49,21]
    - [1048,1000,34,17]
    - [1134,999,66,24]
    - [1236,1006,66,17]
    - [1343,998,48,25]

  follow:                                               [1575,888,76,13]
  result:                                               [271,454,248,41]
  
  sidebet panel:                                        [1679,529,20,95]
  sidebet:                                              
   - [1391,204,62,15]
   - [1479,204,67,15]
   - [1577,205,55,13]
   - [1669,204,54,16]

  baccarat:
    player:                                             [572,739,40,29]
    tie:                                                [947,748,36,32]
    banker:                                             [1310,742,47,33]
    player-pair:                                        [684,671,15,11]
    any-pair:                                           [867,668,12,11]
    perfect-pair:                                       [1038,672,12,11]
    banker-pair:                                        [1215,673,13,11]
    player-bonus:                                       [334,722,31,28]
    banker-bonus:                                       [1550,716,11,12]

ImagePath:
  Main:                                                 "\\imgs\\"
  Nav:                                                  "\\imgs\\nav"
  Table:                                                "\\imgs\\tables"
